// <auto-generated />
using System;
using Gantry.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gantry.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727170000_AddTags")]
    partial class AddTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gantry.Api.Data.Entities.Note", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Content").IsRequired().ValueGeneratedOnAdd().HasColumnType("text").HasDefaultValue("");
                    b.Property<DateTime>("CreatedUtc").HasColumnType("timestamptz");
                    b.Property<DateOnly?>("Date").HasColumnType("date");
                    b.Property<bool>("IsScratchPad").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false);
                    b.Property<Guid?>("ProjectId").HasColumnType("uuid");
                    b.Property<string>("Title").HasColumnType("text");
                    b.Property<DateTime>("UpdatedUtc").HasColumnType("timestamptz");
                    b.HasKey("Id");
                    b.HasIndex("ProjectId");
                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Gantry.Api.Data.Entities.Project", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Color").HasColumnType("text");
                    b.Property<DateTime>("CreatedUtc").HasColumnType("timestamptz");
                    b.Property<string>("Description").HasColumnType("text");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.Property<Guid?>("ParentProjectId").HasColumnType("uuid");
                    b.Property<string>("Settings").HasColumnType("jsonb");
                    b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasColumnType("text").HasDefaultValue("Active");
                    b.Property<DateTime>("UpdatedUtc").HasColumnType("timestamptz");
                    b.HasKey("Id");
                    b.HasIndex("ParentProjectId");
                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Gantry.Api.Data.Entities.ProjectEnvironment", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("BaseUrl").HasColumnType("text");
                    b.Property<DateTime>("CreatedUtc").HasColumnType("timestamptz");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.Property<Guid?>("ProjectId").HasColumnType("uuid");
                    b.Property<int>("SortOrder").HasColumnType("integer");
                    b.Property<DateTime>("UpdatedUtc").HasColumnType("timestamptz");
                    b.HasKey("Id");
                    b.HasIndex("ProjectId");
                    b.ToTable("Environments");
                });

            modelBuilder.Entity("Gantry.Api.Data.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedUtc").HasColumnType("timestamptz");
                    b.Property<string>("Description").HasColumnType("text");
                    b.Property<Guid?>("EnvironmentId").HasColumnType("uuid");
                    b.Property<string>("Location").IsRequired().HasColumnType("text");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.Property<Guid?>("ProjectId").HasColumnType("uuid");
                    b.Property<int>("SortOrder").HasColumnType("integer");
                    b.Property<string>("Type").IsRequired().ValueGeneratedOnAdd().HasColumnType("text").HasDefaultValue("Website");
                    b.Property<DateTime>("UpdatedUtc").HasColumnType("timestamptz");
                    b.HasKey("Id");
                    b.HasIndex("EnvironmentId");
                    b.HasIndex("ProjectId");
                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Gantry.Api.Data.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Color").HasColumnType("text");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("Name").IsUnique();
                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Gantry.Api.Data.Entities.Todo", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime?>("CompletedUtc").HasColumnType("timestamptz");
                    b.Property<DateTime>("CreatedUtc").HasColumnType("timestamptz");
                    b.Property<DateTime?>("DeletedUtc").HasColumnType("timestamptz");
                    b.Property<string>("Description").HasColumnType("text");
                    b.Property<DateOnly?>("DueDate").HasColumnType("date");
                    b.Property<int?>("EstimatedMinutes").HasColumnType("integer");
                    b.Property<bool>("IsPinned").HasColumnType("boolean");
                    b.Property<string>("Priority").IsRequired().ValueGeneratedOnAdd().HasColumnType("text").HasDefaultValue("Medium");
                    b.Property<Guid?>("ProjectId").HasColumnType("uuid");
                    b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasColumnType("text").HasDefaultValue("Todo");
                    b.Property<string>("Title").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("UpdatedUtc").HasColumnType("timestamptz");
                    b.HasKey("Id");
                    b.HasIndex("ProjectId");
                    b.ToTable("Todos");
                });

            modelBuilder.Entity("Gantry.Api.Data.Entities.Win", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedUtc").HasColumnType("timestamptz");
                    b.Property<DateOnly>("Date").HasColumnType("date");
                    b.Property<string>("Description").HasColumnType("text");
                    b.Property<string>("Impact").HasColumnType("text");
                    b.Property<Guid?>("ProjectId").HasColumnType("uuid");
                    b.Property<string>("Title").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("UpdatedUtc").HasColumnType("timestamptz");
                    b.HasKey("Id");
                    b.HasIndex("Date");
                    b.HasIndex("ProjectId");
                    b.ToTable("Wins");
                });

            modelBuilder.Entity("NoteTags", b =>
                {
                    b.Property<Guid>("NoteId").HasColumnType("uuid");
                    b.Property<Guid>("TagId").HasColumnType("uuid");
                    b.HasKey("NoteId", "TagId");
                    b.HasIndex("TagId");
                    b.ToTable("NoteTags");
                });

            modelBuilder.Entity("ProjectTags", b =>
                {
                    b.Property<Guid>("ProjectId").HasColumnType("uuid");
                    b.Property<Guid>("TagId").HasColumnType("uuid");
                    b.HasKey("ProjectId", "TagId");
                    b.HasIndex("TagId");
                    b.ToTable("ProjectTags");
                });

            modelBuilder.Entity("ResourceTags", b =>
                {
                    b.Property<Guid>("ResourceId").HasColumnType("uuid");
                    b.Property<Guid>("TagId").HasColumnType("uuid");
                    b.HasKey("ResourceId", "TagId");
                    b.HasIndex("TagId");
                    b.ToTable("ResourceTags");
                });

            modelBuilder.Entity("TodoTags", b =>
                {
                    b.Property<Guid>("TodoId").HasColumnType("uuid");
                    b.Property<Guid>("TagId").HasColumnType("uuid");
                    b.HasKey("TodoId", "TagId");
                    b.HasIndex("TagId");
                    b.ToTable("TodoTags");
                });

            modelBuilder.Entity("WinTags", b =>
                {
                    b.Property<Guid>("WinId").HasColumnType("uuid");
                    b.Property<Guid>("TagId").HasColumnType("uuid");
                    b.HasKey("WinId", "TagId");
                    b.HasIndex("TagId");
                    b.ToTable("WinTags");
                });

            modelBuilder.Entity("Gantry.Api.Data.Entities.Note", b =>
                {
                    b.HasOne("Gantry.Api.Data.Entities.Project", "Project").WithMany().HasForeignKey("ProjectId").IsRequired(false).OnDelete(DeleteBehavior.Cascade);
                    b.Navigation("Project");
                });

            modelBuilder.Entity("Gantry.Api.Data.Entities.ProjectEnvironment", b =>
                {
                    b.HasOne("Gantry.Api.Data.Entities.Project", "Project").WithMany().HasForeignKey("ProjectId").IsRequired(false).OnDelete(DeleteBehavior.Cascade);
                    b.Navigation("Project");
                });

            modelBuilder.Entity("Gantry.Api.Data.Entities.Project", b =>
                {
                    b.HasOne("Gantry.Api.Data.Entities.Project", "ParentProject").WithMany("ChildProjects").HasForeignKey("ParentProjectId").OnDelete(DeleteBehavior.Restrict);
                    b.Navigation("ParentProject");
                });

            modelBuilder.Entity("Gantry.Api.Data.Entities.Resource", b =>
                {
                    b.HasOne("Gantry.Api.Data.Entities.ProjectEnvironment", "Environment").WithMany("Resources").HasForeignKey("EnvironmentId").IsRequired(false).OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("Gantry.Api.Data.Entities.Project", "Project").WithMany().HasForeignKey("ProjectId").IsRequired(false).OnDelete(DeleteBehavior.Cascade);
                    b.Navigation("Environment");
                    b.Navigation("Project");
                });

            modelBuilder.Entity("Gantry.Api.Data.Entities.Todo", b =>
                {
                    b.HasOne("Gantry.Api.Data.Entities.Project", "Project").WithMany().HasForeignKey("ProjectId").OnDelete(DeleteBehavior.Cascade);
                    b.Navigation("Project");
                });

            modelBuilder.Entity("Gantry.Api.Data.Entities.Win", b =>
                {
                    b.HasOne("Gantry.Api.Data.Entities.Project", "Project").WithMany().HasForeignKey("ProjectId").IsRequired(false).OnDelete(DeleteBehavior.Cascade);
                    b.Navigation("Project");
                });

            modelBuilder.Entity("NoteTags", b =>
                {
                    b.HasOne("Gantry.Api.Data.Entities.Note", null).WithMany().HasForeignKey("NoteId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("Gantry.Api.Data.Entities.Tag", null).WithMany().HasForeignKey("TagId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("ProjectTags", b =>
                {
                    b.HasOne("Gantry.Api.Data.Entities.Project", null).WithMany().HasForeignKey("ProjectId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("Gantry.Api.Data.Entities.Tag", null).WithMany().HasForeignKey("TagId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("ResourceTags", b =>
                {
                    b.HasOne("Gantry.Api.Data.Entities.Resource", null).WithMany().HasForeignKey("ResourceId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("Gantry.Api.Data.Entities.Tag", null).WithMany().HasForeignKey("TagId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("TodoTags", b =>
                {
                    b.HasOne("Gantry.Api.Data.Entities.Todo", null).WithMany().HasForeignKey("TodoId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("Gantry.Api.Data.Entities.Tag", null).WithMany().HasForeignKey("TagId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("WinTags", b =>
                {
                    b.HasOne("Gantry.Api.Data.Entities.Win", null).WithMany().HasForeignKey("WinId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("Gantry.Api.Data.Entities.Tag", null).WithMany().HasForeignKey("TagId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Gantry.Api.Data.Entities.Project", b =>
                {
                    b.Navigation("ChildProjects");
                });

            modelBuilder.Entity("Gantry.Api.Data.Entities.ProjectEnvironment", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
